openapi: 3.0.3
info:
  title: Hospital Management API
  description: API for managing patients, doctors, appointments, and medical records.
  version: 1.0.0

servers:
  - url: 'https'  # Base URL for the API

paths:
  # Appointment Endpoints (/appointments)
  /appointments:
    get:
      summary: List all appointments
      responses:
        '200':
          description: Appointments retrieved
        '400':
          description: Error retrieving appointments
    post:
      summary: Create new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment created
        '400':
          description: Error creating appointment

  /appointments/{id}:
    get:
      summary: Retrieve specific appointment by ID
      parameters:
        - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: Appointment retrieved
        '404':
          description: Appointment not found
    put:
      summary: Update specific appointment by ID
      parameters:
        - $ref: '#/components/parameters/IdPathParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Appointment updated
        '400':
          description: Error updating appointment
    delete:
      summary: Delete specific appointment by ID
      parameters:
        - $ref: '#/components/parameters/IdPathParam'
      responses:
        '204':
          description: Appointment deleted
        '404':
          description: Appointment not found

  /appointments/{id}/medical-record:
    get:
      summary: Retrieve medical record for specific appointment
      parameters:
        - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: Medical record retrieved
        '404':
          description: Appointment or medical record not found

# Components Section
components:
  parameters:
    IdPathParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64

  # Schemas for request/response bodies
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        appointmentDate:
          type: string
          format: date-time
        status:
          type: string
        notes:
          type: string
        patientId:
          type: integer
          format: int64
        doctorId:
          type: integer
          format: int64